[tool.poetry]
name = "project-request-scripts"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.0"
gen3 = "^4.26.1"
requests = "^2.32.3"
pytest-shutil = "^1.8.1"
gitpython = "^3.1.44"
dictionaryutils = {git = "https://github.com/chicagopcdc/dictionaryutils.git", rev = "pcdc_dev"}
pypfb = {git = "https://github.com/chicagopcdc/pypfb.git", rev = "0.2.3"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"